packages:
  - packages/*

catalogs:
  prisma:
    prisma: latest

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
