-- CreateEnum
CREATE TYPE "Color" AS ENUM ('RED', 'ORANGE', 'AMBER', 'YELLOW', 'LIME', 'GREEN', 'EMERALD', 'TEAL', 'CYAN', 'SKY', 'BLUE', 'INDIGO', 'VIOLET', 'PURPLE', 'FUCHSIA', 'PINK', 'ROSE', 'BLACK', 'WHITE', 'GRAY', 'SLATE', 'STONE', 'ZINC', 'NEON_GREEN', 'NEON_PINK', 'MINT', 'AQUA', 'TURQUOISE', 'BRONZE', 'GOLD', 'SILVER', 'COPPER', 'MAROON', 'OLIVE', 'NAVY', 'LAVENDER', 'BEIGE', 'PEACH', 'BROWN', 'CHARCOAL', 'MAGENTA', 'CORAL', 'SAPPHIRE', 'RUBY', 'SAND', 'MUSTARD', 'ICE', 'JADE', 'PLUM', 'SEAFOAM', 'INDIGO_DARK', 'LIME_DARK', 'BERRY', 'MOSS', 'FLAMINGO', 'ICE_BLUE', 'MULBERRY', 'MANGO', 'OBSIDIAN', 'WISTERIA');

-- AlterTable
ALTER TABLE "project" ADD COLUMN     "color" "Color" DEFAULT 'CYAN',
ALTER COLUMN "icon" SET DEFAULT 'building-2';
